import type { Config } from "tailwindcss";

// "Luminous Professional" design system (Material 3 tokens).
// Nguồn: stitch_flowie_project_management/luminous_professional/DESIGN.md
const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb596",
        "on-surface-variant": "#434655",
        "secondary-fixed-dim": "#c4c7c9",
        "on-tertiary-container": "#ffede6",
        "primary-container": "#2563eb",
        background: "#f8f9ff",
        "on-error": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5eeff",
        "on-secondary-fixed-variant": "#444749",
        tertiary: "#943700",
        "secondary-container": "#e0e3e5",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "on-tertiary-fixed": "#360f00",
        "on-primary-fixed": "#00174b",
        "inverse-on-surface": "#eaf1ff",
        "surface-dim": "#cbdbf5",
        "tertiary-container": "#bc4800",
        "secondary-fixed": "#e0e3e5",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        outline: "#737686",
        surface: "#f8f9ff",
        "on-secondary-container": "#626567",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "surface-container-high": "#dce9ff",
        "outline-variant": "#c3c6d7",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        secondary: "#5c5f61",
        "primary-fixed-dim": "#b4c5ff",
        primary: "#004ac6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dbe1ff",
        error: "#ba1a1a",
        "on-secondary-fixed": "#191c1e",
        "surface-tint": "#0053db",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-primary-container": "#eeefff",
        "surface-variant": "#d3e4fe",
        "inverse-primary": "#b4c5ff",
        success: "#3a7d44",
        "success-container": "#c9f2d0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "margin-mobile": "16px",
        sm: "8px",
        lg: "24px",
        xl: "32px",
        "margin-desktop": "32px",
        xs: "4px",
        md: "16px",
        gutter: "16px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      boxShadow: {
        popover: "0 4px 12px rgba(0, 0, 0, 0.05)",
        modal: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};

export default config;
